### ISSUE TITLE
Tag an official stable release

### ISSUE THREAD

**Issue by johnschultz** [awslabs/distill-cli#11]
Any plans to tag an official stable release?

I'd like to create a Homebrew formulae to install Distill more easily, but according to their guidelines, all software must have an official tagged release.

From https://docs.brew.sh/Acceptable-Formulae#stable-versions:

> Formulae in the core repository must have a stable version tagged by the upstream project. Tarballs are preferred to Git checkouts, and tarballs should include the version in the filename whenever possible.
>
>We don’t accept software without a tagged version because they regularly break due to upstream changes and we can’t provide [bottles](https://docs.brew.sh/Bottles) for them.

**Comment by jbnunn** [comment]
Good callout, thanks @johnschultz -- just tagged as beta/non-prod, let me know if that doesn't work for Homebrew.
