### ISSUE TITLE
S3 object

### ISSUE THREAD

**Issue by jyjohnson** [awslabs/distill-cli#8]
Curious if the default behavior could be to delete the media file (S3 object) after transcription/summarization? Why does it need to hang around? Thanks.

**Comment by sankeyraut** [comment]
I think we can add a flag to indicate that the s3 file can be deleted post processing

**Comment by jbnunn** [comment]
Good plan. Happy to implement this unless one of you want to submit a PR, @jyjohnson @sankeyraut

**Comment by TheWitcherish** [comment]
Hi,
I saw this issue and wanted to contribute to this CLI tool :)
I implemented the flag to indicate that the s3 file can be deleted post processing @jyjohnson  @sankeyraut ([see PR](https://github.com/awslabs/distill-cli/pull/9)).

Do not consider this PR it if it was already implemented or you were already working on it.

**Comment by TheWitcherish** [comment]
This issue has been addressed and implemented within the merged PR above. It can be closed @jyjohnson.

**Comment by jbnunn** [comment]
Thanks you @ajohn-wick and @jyjohnson -- closing
